In [7]:
import pandas as pd
import numpy as np
import os
import gzip
import pickle
import re
import copy
from tqdm import tqdm

In [8]:
df = pd.read_csv('hardware_efficiency.csv') # date,hardware_name,TH/J

max_efficiency = pd.read_csv('../../hardwarelist/Bitcoin max updated2.csv') # rows are date,max (TH/J),archaicity (TH/J)

def get_max_efficiency(date):
    date = str(date)[:10]
    try:
        return max_efficiency[max_efficiency['date'] == date]['max (TH/J)'].values[0]
    except:
        return -1
    

# print rows where TH/J is larger than the max efficiency for that date
df['max_efficiency'] = df['date'].apply(lambda x: get_max_efficiency(x))
df_bad = df[df['TH/J'] > df['max_efficiency']*1.2]
df_bad

,date,hardware_name,TH/J,max_efficiency
193,2011-06-10 15:04:00,core i7 2600k,1.860000e-05,0.000004
512,2011-08-18 07:02:54,core i7 2600k,1.860000e-05,0.000004
804,2012-03-05 23:46:04,7850,1.910000e-04,0.000023
937,2012-06-21 21:29:27,core i7 3930k,6.660000e-05,0.000023
1291,2013-06-06 22:17:13,knc jupiter,4.000000e-04,0.000250
1300,2013-06-07 23:09:14,knc jupiter,4.000000e-04,0.000250
1305,2013-06-10 20:10:03,knc jupiter,4.000000e-04,0.000250
1316,2013-06-21 17:06:38,knc jupiter,4.000000e-04,0.000250
1317,2013-06-21 20:03:36,knc jupiter,4.000000e-04,0.000250
1390,2013-09-18 17:24:52,red/bluefury,1.040000e-03,0.000400
1434,2013-12-31 18:12:37,aisen a1 pro,1.045455e-02,0.001429
1441,2014-01-21 19:32:20,aisen a1 pro,1.045455e-02,0.001429
1480,2014-04-21 11:15:24,aisen a1 pro,1.045455e-02,0.002000
1486,2014-05-30 10:10:11,aisen a1 pro,1.045455e-02,0.002000
1490,2014-06-23 10:39:26,aisen a1 pro,1.045455e-02,0.002000
1491,2014-06-28 22:03:22,aisen a1 pro,1.045455e-02,0.002000
1497,2014-07-18 04:11:01,aisen a1 pro,1.045455e-02,0.002000
1498,2014-07-18 12:28:46,aisen a1 pro,1.045455e-02,0.002000
1500,2014-07-27 03:51:55,aisen a1 pro,1.045455e-02,0.003160
1504,2014-09-05 03:28:05,aisen a1 pro,1.045455e-02,0.003160
1522,2015-02-21 14:54:29,aisen a1 pro,1.045455e-02,0.005350
1699,2023-01-30 23:51:50,canaan avalonminer 1166 pro,2.382353e-02,-1.000000
1700,2023-03-12 03:11:25,canaan avalonminer 1166 pro,2.382353e-02,-1.000000
1701,2023-03-16 06:11:20,antminer s9,1.018200e-02,-1.000000
1702,2023-04-10 09:33:49,avalon741,6.350000e-03,-1.000000
1703,2023-04-30 13:21:49,aisen a1 pro,1.045455e-02,-1.000000
1704,2023-05-23 11:02:41,avalon721,6.000000e-03,-1.000000
1705,2023-05-23 11:02:41,avalon741,6.350000e-03,-1.000000
1706,2023-05-23 11:02:41,allwinner a10,5.680000e-07,-1.000000
1707,2023-09-21 00:29:48,bitmain antminer s19,2.923077e-02,-1.000000

In [ ]:
# import pandas as pd


# # Assuming the 'Date' column in max_efficiency_table is in a format that can be converted to datetime
# max_efficiency['date'] = pd.to_datetime(max_efficiency['date'])

# data = pd.read_csv('datasets/extracted/final3.csv')
# data["date"] = data["date"].apply(lambda x: x[:10])
# data2 = pd.read_csv('datasets/extracted/pre_2018.csv')
# data = pd.concat([data2[["date","row_index","hardware_name","TH/J"]], data[["date","row_index","hardware_name","TH/J"]]])



# # delete rows where TH/J is larger than the max efficiency for that date
# data['max_efficiency'] = data['date'].apply(lambda x: get_max_efficiency(x))
# data = data[data['TH/J'] <= data['max_efficiency']*1.01]

# data.to_csv('datasets/extracted/merged.csv', index=False)

# # Convert the 'date' column to a datetime format
# data['date'] = pd.to_datetime(data['date'])

# # Extract year from the 'date' column and create a new column 'year'
# data['year'] = data['date'].dt.year

# data.to_csv('plotdata.csv', index=False)